name: xeusAvecClangd
channels:
  - conda-forge
dependencies:
  - xeus-cling=0.12.0
  - notebook
  - python>=3.6
  - jupyterlab>=3.0.0,<4.0.0a0
  - jupyterlab-lsp>=3.4.0
  - jupyter-lsp>=1.1.3
  - python-language-server
