#!/bin/bash
set -ex

# jupyter labextension install --no-build '@krassowski/jupyterlab-lsp@3.5.0'
pip install jupyterlab-lsp=3.5.0
jupyter lab build --dev-build=False --minimize=False

cd ~

# git clone https://github.com/Kapral67/llvm-project.git

jupyter lab --generate-config
wget https://github.com/Kapral67/llvm-project/releases/download/jupyter/clangd_13.zip
7z x clangd_13.zip
cd ~/clangd_13/bin
chmod a+x clangd
echo 'export PATH=$PATH:/home/jovyan/clangd_13/bin/' >> ~/.bashrc
source ~/.bashrc
cd ~/.jupyter
rm -f jupyter_lab_config.py
cp ~/clangd_13/jupyter_lab_config.py .
cd ~

jupyter serverextension list
jupyter server extension list
jupyter labextension list
