#!/usr/bin/env bash
set -eux

jupyter labextension install --no-build '@krassowski/jupyterlab-lsp@3.4.1'
jupyter lab build --dev-build=False --minimize=False

cd ~
jupyter notebook --generate-config
wget https://github.com/Kapral67/llvm-project/releases/download/v0.13.1/clangd_13.zip
7z x clangd_13.zip
cd ~/.jupyter
cp ~/clangd_13/jupyter_notebook_config.py .
cd ~
