#!/bin/bash
set -ex

# jupyter labextension install --no-build '@krassowski/jupyterlab-lsp@3.5.0'
pip install jupyterlab-lsp==3.5.0
jupyter lab build --dev-build=False --minimize=False

cd ~

7z x examples.zip

# git clone https://github.com/Kapral67/llvm-project.git

jupyter notebook --generate-config
# wget https://github.com/Kapral67/llvm-project/releases/download/jupyter/clangd_13.zip
wget https://github.com/clangd/clangd/releases/download/11.0.0/clangd-linux-11.0.0.zip
# 7z x clangd_13.zip
7z x clangd-linux-11.0.0.zip
# cd ~/clangd_13/bin
cd ~/clangd_11.0.0/bin
chmod a+x clangd
./clangd --version
# echo 'export PATH=$PATH:/home/jovyan/clangd_13/bin/' >> ~/.bashrc
echo 'export PATH=$PATH:/home/jovyan/clangd_11.0.0/bin/' >> ~/.bashrc
source ~/.bashrc
cd ~/.jupyter
rm -f jupyter_notebook_config.py
mv ~/jupyter_notebook_config.py .
cd ~/examples
mkdir .lsp_symlink
cd .lsp_symlink
ln -s /home home
mkdir usr
cd usr
mkdir include
cd include
ln -s /usr/include/c++/ c%2B%2B
mkdir -p x86_64-linux-gnu/c%2B%2B/7/bits/
cd x86_64-linux-gnu/c%2B%2B/7/bits/
cp -s /usr/include/x86_64-linux-gnu/c++/7/bits/*.h .
rm *+*.h
ln -s /usr/include/x86_64-linux-gnu/c++/7/bits/c++allocator.h c%2B%2Ballocator.h
ln -s /usr/include/x86_64-linux-gnu/c++/7/bits/c++config.h c%2B%2Bconfig.h
ln -s /usr/include/x86_64-linux-gnu/c++/7/bits/c++io.h c%2B%2Bio.h
ln -s /usr/include/x86_64-linux-gnu/c++/7/bits/c++locale.h c%2B%2Blocale.h
ln -s /usr/include/x86_64-linux-gnu/c++/7/bits/extc++.h extc%2B%2B.h
ln -s /usr/include/x86_64-linux-gnu/c++/7/bits/stdc++.h stdc%2B%2B.h
ln -s /usr/include/x86_64-linux-gnu/c++/7/bits/stdtr1c++.h stdtr1c%2B%2B.h
cd ..
ln -s /usr/include/x86_64-linux-gnu/c++/7/ext/ ext

cd ~

jupyter serverextension list
jupyter server extension list
jupyter labextension list
