#!/bin/bash
set -ex

pip install jupyterlab-lsp==3.8.1 jupyter-lsp==1.4.1
jupyter lab build --dev-build=False --minimize=False

cd ~

7z x examples.zip

jupyter notebook --generate-config
wget https://github.com/Kapral67/Cling-Clangd/releases/download/amd64-dev/xeus-clangd.12.0.1.x86_64.tar.gz
tar -zxf xeus-clangd.12.0.1.x86_64.tar.gz

chmod a+x ~/xeus-clangd.12.0.1.x86_64/build/bin/clangd

echo 'export PATH=$PATH:/home/jovyan/xeus-clangd.12.0.1.x86_64/build/bin/' >> ~/.bashrc
source ~/.bashrc
cd ~/.jupyter
rm -f jupyter_notebook_config.py
mv ~/jupyter_notebook_config.py .
cd ~/examples
mkdir .lsp_symlink
cd .lsp_symlink
ln -s /home home
mkdir usr
cd usr
mkdir include
cd include
ln -s /usr/include/c++/ c%2B%2B
mkdir -p x86_64-linux-gnu/c%2B%2B/7/bits/
cd x86_64-linux-gnu/c%2B%2B/7/bits/
cp -s /usr/include/x86_64-linux-gnu/c++/7/bits/*.h .
rm *+*.h
ln -s /usr/include/x86_64-linux-gnu/c++/7/bits/c++allocator.h c%2B%2Ballocator.h
ln -s /usr/include/x86_64-linux-gnu/c++/7/bits/c++config.h c%2B%2Bconfig.h
ln -s /usr/include/x86_64-linux-gnu/c++/7/bits/c++io.h c%2B%2Bio.h
ln -s /usr/include/x86_64-linux-gnu/c++/7/bits/c++locale.h c%2B%2Blocale.h
ln -s /usr/include/x86_64-linux-gnu/c++/7/bits/extc++.h extc%2B%2B.h
ln -s /usr/include/x86_64-linux-gnu/c++/7/bits/stdc++.h stdc%2B%2B.h
ln -s /usr/include/x86_64-linux-gnu/c++/7/bits/stdtr1c++.h stdtr1c%2B%2B.h
cd ..
ln -s /usr/include/x86_64-linux-gnu/c++/7/ext/ ext

cd ~

jupyter serverextension list
jupyter server extension list
jupyter labextension list
